"""Crea new_column in TestModel tabla Test

Revision ID: dfd96e01c0e2
Revises: a5a8f53ac0dc
Create Date: 2022-08-06 17:30:18.184794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd96e01c0e2'
down_revision = 'a5a8f53ac0dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Test', sa.Column('new_column', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Test', 'new_column')
    # ### end Alembic commands ###
